name             'lvm_mount'
maintainer       'JamesJJ'
maintainer_email 'JamesJJ@users.noreply.github.com'
license          'MIT'
description      'Create an LVM volume, format it and mount it'
long_description      'Create an LVM volume, format it and mount it'
version          '0.1.4'
